### ISSUE TITLE
<Feature Request> Keybinds for sharemap and sharepins

### ISSUE THREAD

**Issue by Spiricore** [rolopogo/ValheimMods#1]
I would love to use this to replace several other mods I'm using and pass it on to my friends, but not having keybinds for the share commands limits accessibility for people too lazy to type them every time.

For example, Map Sync (https://www.nexusmods.com/valheim/mods/42) uses F10 to share map data.

Thanks for your work! This has a great feature set.

**Comment by rolopogo** [comment]
Added in 1.1.0
F10 and F9 by default, change these bindings in the config file

**Comment by rolopogo** [comment]
#

**Comment by Blend3rman** [comment]
> Added in 1.1.0
> F10 and F9 by default, change these bindings in the config file

You should mention this somewhere in the mod description on the sites hosting this.
