### ISSUE TITLE
Valheim Console Spam

### ISSUE THREAD

**Issue by FunkyBigdog** [rolopogo/ValheimMods#11]
Not really a big issue as far as I can see, but since the update (1.2.1) my console is spamming [Info   : Unity Log] 0 0 constantly.  Disabling this mod in general resolves it, but as of right now, it does not seem to have any adverse affects on game play.  This is happening in both my singleplayer world and the dedicated server I run for my friends.  Although in the short time I have seen it in singleplayer, the zeroes did increment up to 2 ([Info   : Unity Log] 2 2).

Btw the last update is working well for me and my friends on my dedicated server regarding the fps, thanks!

**Comment by rolopogo** [comment]
The number refers to the number of carts present and the number of cart pins displayed, I accidentally left it in from testing! It'll be gone next update

**Comment by JCimbal** [comment]
A short fix is deactivating cart-tracking instead of disabling the whole (very useful, thank you) mod.

**Comment by rolopogo** [comment]
Fixed in 1.2.2
