### ISSUE TITLE
CustomSails: Can't set URL

### ISSUE THREAD

**Issue by PsycsX** [rolopogo/ValheimMods#18]
Hello,

I installed CustomSails the day that Valheim patch 0.148.6 came out.  I see the plugin loads, but I can't interact with the boat to set the URL like the video shows.  I tried changing the key used, as well as setting "RequireKeyPress = false" in config, but no luck.

When I load a world, I see the following error text in the BepInEx console window:

```
[Error  : Unity Log] MissingMethodException: bool PrivateArea.CheckAccess(UnityEngine.Vector3,single,bool)
Stack trace:
CustomSails.ShipSailUrlSetter.UpdateText () (at <92ad433a205443ee96b908f6525e1cea>:0)
CustomSails.ShipSailUrlSetter.Awake () (at <92ad433a205443ee96b908f6525e1cea>:0)
UnityEngine.GameObject:AddComponent()
CustomSails.Ship_Patch:Ship_Awake(Ship)
Ship:DMD<Ship::Awake>(Ship)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateObjectsSorted(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:CreateDestroyObjects()
ZNetScene:Update()

**Comment by rolopogo** [comment]
Fixed in 1.1.0 by removing ward restrictions.
https://valheim.thunderstore.io/package/Rolo/CustomSails/
