### ISSUE TITLE
Basement documentation mismatch

### ISSUE THREAD

**Issue by rysson** [rolopogo/ValheimMods#20]
In `ValheimMods/Basement/README` is `CustomSails` description.

BTW. Is Basement client side only mod? What see another players?
<del>I'm asking because I can not find Basement item in misc page then I can't build it.</del> – sorry, I missed HookGenPatcher in my manual installation. Now I can build Basement.

**Comment by rolopogo** [comment]
Oopsie. I copied the custom sails to avoid setting up all the references each time. I'll get that fixed!
