### ISSUE TITLE
BASEMENT

### ISSUE THREAD

**Issue by gagaroth99** [rolopogo/ValheimMods#25]
I can't create a basement, I have the necessary materials, but when I select the basement to create it, it doesn't appear on the screen. if i click on the ground to create it, the only action that happens is like i'm using the hammer to fix something with damage

**Comment by anderskronquist** [comment]
Seconded. I tried both on a solo game as well as on a dedicated server.

**Comment by sutex** [comment]
Yep same, no icon nothing showing to place

**Comment by IceyCold** [comment]
Same here
Have tried with other mods and with only this one

**Comment by rolopogo** [comment]
Hi guys, any errors in console? It seems like the prefab isn't being registered properly. Can you share the output of your console log where it lists mods loading in? I wonder if it's a version issue with vlib or hooks

**Comment by anderskronquist** [comment]
The only thing I saw was:
[Info   :  Basement] No suitable material found to replace: void

No errors in console. Check out the log here (local world login) - I attempted to place down the Basement misc thingy just to see if that caused anything.


https://pastebin.com/dWCMLSnJ

**Comment by IceyCold** [comment]
Same as ander
[Player.log](https://github.com/rolopogo/ValheimMods/files/6306473/Player.log)

**Comment by jsza** [comment]
It works for me if I install 1.0.0 from https://valheim.thunderstore.io/package/Rolo/Basement/

Not sure what changed in 1.0.1; looks the changes aren't available here in the repo?

**Comment by IceyCold** [comment]
Installed 1.0.0 and works fine for me also

**Comment by rolopogo** [comment]
Super strange, 1.0.1 just changes the material names and how they are looked up against the vanilla materials. I've pushed the changes.

**Comment by jsza** [comment]
It seems the basement prefab has `Piece.m_repair` set to `True` which prevents it from being placed. Hope that helps? Not sure how resource packs work, been poking around in Unity Explorer.

**Comment by eldos1** [comment]
I am getting a Bepinex  loading error in the log window.  Warning: BepInEx]Skipping [Basement 1.0.1] because newer version exists [Basement 1.0.1] 
Yes, uninstalled and reinstalled 1.0.1 files from .zip

**Comment by PugLyf** [comment]
Having the same problem as others here. In the hammer menu when I select to build the basement it just treats it as if I'm trying to repair using the hammer, as shown in these images. Don't know if this helps identify the problem at all.

![image](https://user-images.githubusercontent.com/28744016/115133557-5991cb00-9fc6-11eb-9eed-9e89d91a39eb.png)
![image](https://user-images.githubusercontent.com/28744016/115133559-644c6000-9fc6-11eb-94e2-0c46ccf9ff04.png)

**Comment by eldos1** [comment]
Basement 1.0.2 has solved my problem and is working. Thank You-
