### ISSUE TITLE
Null pointer error causes character to be created at spawn point (bed or origin spawn) and character to be stuck in create/destroy cycle.

### ISSUE THREAD

**Issue by biouxtai** [rolopogo/ValheimMods#30]
This is caused by the Basement mod.

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponent[T] () (at <51725b129ecd4967a9a213c1ae65b295>:0)
Player.UpdateKnownRecipesList () (at <64e3050735a54dbb8762d6e3432a1162>:0)
ValheimLib.ODB.ObjectDBHelper.ReloadKnownRecipes (On.Player+orig_Load orig, Player self, ZPackage pkg) (at <66dec4d05d8743eb8424a906129f16d8>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Player::Load>?1742125056(Player,ZPackage)
PlayerProfile.LoadPlayerData (Player player) (at <64e3050735a54dbb8762d6e3432a1162>:0)
Game.SpawnPlayer (UnityEngine.Vector3 spawnPoint) (at <64e3050735a54dbb8762d6e3432a1162>:0)
Game.UpdateRespawn (System.Single dt) (at <64e3050735a54dbb8762d6e3432a1162>:0)
Game.FixedUpdate () (at <64e3050735a54dbb8762d6e3432a1162>:0)

[Info   : Unity Log] 04/25/2021 22:42:43: Destroying old local player

Disabling the Basement mod eliminates the error.

Thunderstore Mod Manager
mods installed:
BepInExPack_Valheim by denikson
BetterArchery by ishid4
ValheimLib by ValheimModding
HookGenPatcher by ValheimModding
Basement by Rolo
ItemDrawers by makail
MapSyncMod by nashy
BetterUI by Masa
Better_Signs by KG
SpeedyPaths by Nextek
Build_Camera by gittywithexcitement
Veinmine by WiseHorror
UseEquipmentInWater by LVH-IT
NonrestrictedPortals by xAfflict
TrashItems by virtuaCode
ValheimNetworkOptimizer by TripleSteel
Softcore_Death by dch
QuickStack by damnsneaker
EquipmentAndQuickSlots by RandyKnapp
PlantGrowProgress by Smallo
MassFarming by Xeio
QuickConnect by bdew
Locator by purpledxd
PreWorkout by Xenofell
NoStamCosts by BasilPanda
DaisyChain by Rolo
CustomSails by Rolo
ColorfulSigns by Tekla
BepInEx_ConfigurationManager by TJzilla
SkillBasedCarryweight by kassent
InteractWhileBuilding by tonsit
ChaseMods_JumpAltersFallingDamage by chase000
Lead by xiaoxiao921
Gizmo by Rolo
FearFire by Zer0Krypt
PlantAnywhere by nDeavor
Craft_From_Containers_by_aedenthorn by frenchiveruti
UnfrightenTamedAnimals by chase000
NameTamedAnimals by Barril
BiggerBoatMapExploreRadius by nearbear
PreventAccidentalInteraction by PhantomGamers
DeathPenalty by Crystal
Heightmap_Unlimited by Menthus
MoreSlots by Fang86
MultiCraft by MaxiMods
CookingStationTweaks by digitiliad

**Comment by rolopogo** [comment]
I've seen this a couple of times and I'm not 100% sure what's causing it. Relogging seems to stop it, but it can happen again at login, which can be real frustrating

**Comment by ddanese** [comment]
Unfortunately for me, I've only ever seen it at login and once it starts, it won't stop until I disable the basement mod. I'm wondering if the ObjectDB isn't ready due to some kinda latency at whatever point the character spawning in tries to access it. All I can see is the result which is a ton of log spam. There are two different messages. One is what I posted. The other I didn't capture, but has a different message about 'Object found at custom spawn point' then the message about destroying the character and recreating. Endless cycle for either though.

**Comment by biouxtai** [comment]
Unfortunately for me, I've only ever seen it at login and once it starts, it won't stop until I disable the basement mod. I'm wondering if the ObjectDB isn't ready due to some kinda latency at whatever point the character spawning in tries to access it. All I can see is the result which is a ton of log spam. There are two different messages. One is what I posted. The other I didn't capture, but has a different message about 'Object found at custom spawn point' then the message about destroying the character and recreating. Endless cycle for either though.

I'll see if I can get a copy of that second error to add here. It might shed more light?

**Comment by biouxtai** [comment]
Looks like it might be a conflict with Equipment and Quickslots.  Just had the error happen again and all those additional slots were emptied all items in them lost.
