### ISSUE TITLE
how do I open  ValheimMods/Basement/Basement/Resources/Basement

### ISSUE THREAD

**Issue by tg08096** [rolopogo/ValheimMods#40]
First I want to thank you for sharing your work AND releasing under the MIT license. 

I'm trying to edit the basement file to so I can increase the size of the area to build custom dungeons. I am a complete noob and the steps I have taken were I downloaded the file, downloaded a hex editor to figure out what kind of file it was, downloaded unity hub correctly (finally), and installed unity 2019.4.24f1. Now I'm stuck. Figured I'd take a shot at asking. .

Like I said I'm a noob but perfectly content banging rocks together until I get sparks!

Thanks again,
tg

**Comment by rolopogo** [comment]
I've uploaded unity packages for both crafty carts and basement so you can import them into your own projects for modification. 

You will also need to have the valheim .dlls imported in your project (assembly_blah.dll) for the attached behaviours to work.
