### ISSUE TITLE
Unable to see other players on the map when they don't have this mod

### ISSUE THREAD

**Issue by VirtueAvatar** [rolopogo/ValheimMods#7]
On the map, other players who don't have the mod installed were able to see me and another player who had installed the mod, but they were still able to see us.

**Comment by VirtueAvatar** [comment]
This seems to apply to anyone - if you have the mod installed, you will randomly not see others on the map even when their map visibility installed. Seems to occasionally fix itself for one person but not the other on re-login.

Others who don't have the mod installed can still see everyone whether they have the mod installed or not.

**Comment by rolopogo** [comment]
This should be fixed in 1.1.2, which I just pushed to Thunderstore!
