### ISSUE TITLE
Multiplayer not shown on map

### ISSUE THREAD

**Issue by kennettleung515** [rolopogo/ValheimMods#9]
For 3 or more multi player using the same server,
map should show all players who checked "view by others player ".
After using this mod, map only shows the latest player who you sent your map to him, and others are disappear from the map.

-Without using mod: player A,B,C,D,E all shown in map
-Used the map and F10(send map) to playerA: playerA still in map, but player B,C,D,E has no player icon in map.
-After F10 to playerA, if I F10 to playerB, it will changed to show playerB, but playerA,C,D,E disappear from map.

**Comment by rolopogo** [comment]
Can you verify this is still happening in 1.1.2?

**Comment by kennettleung515** [comment]
just checked it seems cannot reproduce, thanks
